## *********************************************************
##
## File autogenerated for the iirob_filters package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 245, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [{'upper': 'THRESHOLDFILTER', 'lower': 'thresholdfilter', 'srcline': 124, 'name': 'ThresholdFilter', 'parent': 0, 'srcfile': '/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT::THRESHOLDFILTER', 'field': 'DEFAULT::thresholdfilter', 'state': True, 'parentclass': 'DEFAULT', 'groups': [], 'parameters': [{'srcline': 15, 'description': 'linear threshold', 'max': inf, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/home/user/catkin_ws/devel/share/iirob_filters/cfg/Threshold.cfg', 'name': 'linear_threshold', 'edit_method': '', 'default': 0.0, 'level': 0, 'min': -inf, 'type': 'double'}, {'srcline': 16, 'description': 'angular threshold', 'max': inf, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/home/user/catkin_ws/devel/share/iirob_filters/cfg/Threshold.cfg', 'name': 'angular_threshold', 'edit_method': '', 'default': 0.0, 'level': 0, 'min': -inf, 'type': 'double'}, {'srcline': 17, 'description': 'threshold for double', 'max': inf, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/home/user/catkin_ws/devel/share/iirob_filters/cfg/Threshold.cfg', 'name': 'threshold', 'edit_method': '', 'default': 0.0, 'level': 0, 'min': -inf, 'type': 'double'}], 'type': '', 'id': 1}], 'parameters': [], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

