// *********************************************************
//
// File autogenerated for the iirob_filters package
// by the rosparam_handler package.
// Please do not edit.
//
// ********************************************************/

#pragma once

#include <ros/param.h>
#include <ros/node_handle.h>
#include <rosparam_handler/utilities.hpp>
#ifdef DYNAMIC_RECONFIGURE_FOUND
#include <iirob_filters/ThresholdConfig.h>
#else
struct ThresholdConfig{};
#endif


namespace iirob_filters {

/// \brief Parameter struct generated by rosparam_handler
struct ThresholdParameters {

  using Config = ThresholdConfig;

  ThresholdParameters(const ros::NodeHandle& private_node_handle)
  : globalNamespace{"/"},
    privateNamespace{private_node_handle.getNamespace() + "/"},
    nodeName{rosparam_handler::getNodeName(private_node_handle)} {}

  /// \brief Get values from parameter server
  /// 
  /// Will fail if a value can not be found and no default value is given.
  void fromParamServer(){
    bool success = true;
    success &= rosparam_handler::getParam(privateNamespace + "linear_threshold", linear_threshold, double{0});
    success &= rosparam_handler::getParam(privateNamespace + "angular_threshold", angular_threshold, double{0});
    success &= rosparam_handler::getParam(privateNamespace + "threshold", threshold, double{0});

    if(!success){
      missingParamsWarning();
      rosparam_handler::exit("RosparamHandler: GetParam could net retrieve parameter.");
    }
    ROS_DEBUG_STREAM(*this);
  }

  /// \brief Set parameters on ROS parameter server.
  void toParamServer(){
  rosparam_handler::setParam(privateNamespace + "linear_threshold",linear_threshold);
  rosparam_handler::setParam(privateNamespace + "angular_threshold",angular_threshold);
  rosparam_handler::setParam(privateNamespace + "threshold",threshold);        
  }

  /// \brief Update configurable parameters.
  ///
  /// \param config  dynamic reconfigure struct
  /// \level ?
  void fromConfig(const Config& config, const uint32_t level = 0){
#ifdef DYNAMIC_RECONFIGURE_FOUND
    linear_threshold = config.linear_threshold;
    angular_threshold = config.angular_threshold;
    threshold = config.threshold;
#else
  ROS_FATAL_STREAM("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
  rosparam_handler::exit("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
#endif
  }

  /// \brief Stream operator for printing parameter struct
  friend std::ostream& operator<<(std::ostream& os, const ThresholdParameters& p)
  {
    os << "[" << p.nodeName << "]\nNode " << p.nodeName << " has the following parameters:\n"
      << "	" << p.privateNamespace << "linear_threshold:" << p.linear_threshold << "\n"
      << "	" << p.privateNamespace << "angular_threshold:" << p.angular_threshold << "\n"
      << "	" << p.privateNamespace << "threshold:" << p.threshold << "\n"
;
    return os;
  }

    double linear_threshold; /*!< linear threshold */
  double angular_threshold; /*!< angular threshold */
  double threshold; /*!< threshold for double */

private:
  /// \brief Issue a warning about missing default parameters.
  void missingParamsWarning(){
    ROS_WARN_STREAM("[" << nodeName << "]\nThe following parameters do not have default values and need to be specified:\n"
    );
  }

  const std::string globalNamespace;
  const std::string privateNamespace;
  const std::string nodeName;
};

} // namespace iirob_filters
